### ISSUE TITLE
ModuleNotFoundError: No module named 'chatto_transform'

### ISSUE THREAD

**Issue by brbatv** [spitz-dan-l/postgres_binary_parser#1]
Hello
Thank you for your amazing work

I'm missing the package from chatto_transform.lib.bins import reduce_categories which is used in the schema.py file. 

Where can I get it ? I found this repo but it's missing https://github.com/smartscheduling/chatto-transform-open-source

Thank you very much, I hope you're still here after 4 years, because this parser would be extremely helpful to me right now :D

**Comment by mcrumiller** [comment]
Hi brbatv,

I took a look into this as well. It turns out that `postgres-binary-parser` has its own bins submodule.

To get things to work, I had to make a few changes:

1. add a `setup.py` to the the root directory. Mine looked like this:

```python
from distutils.core import setup
from Cython.Build import cythonize
import numpy as np
import os

setup(
  name = 'postgres-binary-parser',
  ext_modules = cythonize("postgres_binary_parser/psql_binary.pyx"),
  include_dirs=[np.get_include()]
)
```

2. Add an `__init__.py` to the `postgres_binary_parser` folder in which the python package resides.
3. Do the same for chatto-transform package.
4. Open up all .py files in `postgres_binary_parser` and change the imports to load from `.` instead.
5. Change the line that tries to load from `chatto_transform.lib.bins` to `from .lib import bins`.

If you can get `chatto_transform` to install as a module, then try the above steps and fiddle around until you can get `postgres-binary-parser` to install as well. This repo has obviously not been updated in 5 years or so, and so the standard way of installing things in python may have changed since then.

**Comment by spitz-dan-l** [comment]
Hi there, given the recent interest I wanted to say hello.

Thanks for the detailed writeup on fixing! I'm no longer actively maintaining this project and probably won't start it up again, but I will spend some time in coming days fixing this up enough so that it at least runs out of the box.

**Comment by brbatv** [comment]
Thank you guys I was thinking i'll never make it work ... This is indeed working thanks to @mcrumiller solution, juste needed to recompile c code and change local imports. 

The only issue I have is that my table contains a column BIGINT and they are loaded into a numpy.float64 when using the schema num('MyBigIntColumn', int=True), which I think slows down the overall process since it's not natively getting them as ints 

But overall I'm very happy that you are still here @spitz-dan-l I even tried to find you on other social medias for help ... :rofl: 

Even with this conversion problem i'm getting a 10x improvement on loading times... very happy

**Comment by spitz-dan-l** [comment]
Fixed everything up and tested in a fresh virtual environment.

Thanks again @mcrumiller ! Thanks @brbatv for the interest!
